### ISSUE TITLE
pyrgub can't find/read grub.cfg....

### ISSUE THREAD

**Issue by wcrigger** [dvdtoth/coreos-xen#1]
I have tried this on my environment only to get the following error attempting to start the coreos VM:

```
Using config file "/etc/xen/vm4_c04".
Traceback (most recent call last):
  File "/usr/bin/pygrub", line 758, in ?
    chosencfg = run_grub(file, entry, fs)
  File "/usr/bin/pygrub", line 581, in run_grub
    g = Grub(file, fs)
  File "/usr/bin/pygrub", line 223, in __init__
    self.read_config(file, fs)
  File "/usr/bin/pygrub", line 437, in read_config
    if self.cf.filename is None:
AttributeError: Grub instance has no attribute 'cf'
No handlers could be found for logger "xend"
Error: Boot loader didn't return any data!
Usage: xm create <ConfigFile> [options] [vars]
```

This leads me to believe its looking for the bootloader, which has not been configured.  Any suggestions on how how to debug this?

Thanks,
Warren

**Comment by wcrigger** [comment]
Here's my cloud config:  [http://leetnet.com/cloud-configs/vm4_cloud_config.txt]

As you can see, I'm running this with a static IP but otherwise the config is the same as yours hosted on gist.
